title: Brian Eaves # your name (or website title) here
logo: "/images/IMG-6978.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist 
  <br><br>
  Thank you for taking the time to check out my portfolio! If you have any questions about the projects that I have done, please feel free to email me at eavesbriank@gmail.com.
  <br><br>
  <a href="https://www.linkedin.com/in/eavesbrian/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
